### ISSUE TITLE
Replica error if underlying storagepool fs is ZFS

### ISSUE THREAD

**Issue by jomar83** [openebs/jiva#52]
We're running Kubernetes 1.9.7 on ubuntu 16.04 with ZFS. 

If the storagepool is a zfs volume, e.g. root/ebs with the following definition in k8s

```
apiVersion: openebs.io/v1alpha1
kind: StoragePool
metadata:
  name: ebs
  type: hostdir
spec:
  path: "/ebs"
```

the replica containers running

`launch replica --frontendIP x.x.x.x --size 1G /openebs`

fail with

> time="2018-05-25T09:35:16Z" level=info msg="Creating volume /openebs, size 1073741824/512" 
time="2018-05-25T09:35:16Z" level=fatal msg="Error running start replica command: open /openebs/revision.counter: invalid argument" 

If we create an ext4 zvol based storagepool it works. Is this expected behaviour?
